paths:
  vis_out_dir: "./vis/"
  cat_path: "../data/cats/cat_neg_10.json"

object_detector_models:
  od_paths:
    - path: "../data/od_pth/od_small_c0.pth"
      threshold: 0.50
    - path: "../data/od_pth/od_large_c1.pth"
      threshold: 0.75

classifier_model:
  class_path: "../data/class_pth/class_full_train_neg_c10.pth"

adjustables:
  bg_color: "white"
  padding: 0.15
  border: 0
  denest: true
  denest_thold: 0.20
  keep_clickable_elems_only: false
  remove_neg: true
  iou_thold: 0.5
  neg_class_name: "Random"

cuda:
  devices: "0"
